org: idouglas
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
